apiVersion: v2
name: cloudnative-pg
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.1.0"

dependencies:
  - name: cluster
    repository: https://cloudnative-pg.github.io/charts
    version: 0.1.0
  - name: umbrella-app
    repository: "oci://registry.nguyen.local/library"
    alias: pg-cron
    version: 1.0.0